### ISSUE TITLE
Add resource_type setup for those not using bosh to readme

### ISSUE THREAD

**Issue by devdavidkarlsson** [aequitas/concourse-ftp-resource#4]
**Probably something like:** 

- name: ftp-resource-type
  type: docker-image
  source:
    repository: aequitas/ftp-resource
    tag: latest

**Comment by aequitas** [comment]
Sorry for the late response, I have not been paying attention to this repo. This should be fixed by someone else's contribution in https://github.com/aequitas/concourse-ftp-resource/pull/1
